### ISSUE TITLE
pandas.core.groupby.DataError: No numeric types to aggregate

### ISSUE THREAD

**Issue by Mustyy** [sdimi/tv-show-summarization-twitter#1]
My data is in this format
created_at":"Mon May 01 17:16:08 +0000 2017

**Comment by sdimi** [comment]
Please make sure that your original column type is `dtype='datetime64` after applying the `pd.to_datetime` function. In your case, the column type probably is not numerical.

Just check what `df.dtypes` brings

**Comment by Mustyy** [comment]
Hey 
Its actually datetime64
I printed (tweet.index)

1325
DatetimeIndex(['2017-05-10 18:30:25-04:00', '2017-05-10 18:37:54-04:00',
               '2017-05-10 18:57:02-04:00', '2017-05-10 18:34:34-04:00',
               '2017-05-10 18:37:58-04:00', '2017-05-10 18:50:26-04:00',
               '2017-05-10 18:46:08-04:00', '2017-05-10 18:42:51-04:00',
               '2017-05-10 18:43:49-04:00', '2017-05-10 18:54:00-04:00',
               ...
               '2017-05-10 17:23:15-04:00', '2017-05-10 17:25:19-04:00',
               '2017-05-10 17:23:27-04:00', '2017-05-10 17:31:12-04:00',
               '2017-05-10 17:32:56-04:00', '2017-05-10 17:31:32-04:00',
               '2017-05-10 17:34:26-04:00', '2017-05-10 17:31:52-04:00',
               '2017-05-10 17:24:07-04:00', '2017-05-10 17:22:38-04:00'],
              dtype='datetime64[ns, US/Eastern]', name=u'created_at', length=1325, freq=None)

**Comment by sdimi** [comment]
Ok, so the `resample` line creates that error? Probably a new version of pandas breaks that compatibility.

**Comment by Mustyy** [comment]
Hey 
Thanks for getting back to me 
So should I roll back to a previous version of pandas ?

Best Regards,
Mustafa

**Comment by Mustyy** [comment]
Traceback (most recent call last):
  File "tvsummarization.py", line 57, in <module>
    tweets1m = tweets['created_at'].resample('30t').count()
  File "/usr/lib/python2.7/dist-packages/pandas/core/generic.py", line 3643, in resample
    return sampler.resample(self).__finalize__(self)
  File "/usr/lib/python2.7/dist-packages/pandas/tseries/resample.py", line 82, in resample
    rs = self._resample_timestamps()
  File "/usr/lib/python2.7/dist-packages/pandas/tseries/resample.py", line 315, in _resample_timestamps
    result = grouped.aggregate(self._agg_method)
  File "/usr/lib/python2.7/dist-packages/pandas/core/groupby.py", line 2425, in aggregate
    return getattr(self, func_or_funcs)(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pandas/core/groupby.py", line 760, in mean
    return self._cython_agg_general('mean')
  File "/usr/lib/python2.7/dist-packages/pandas/core/groupby.py", line 1215, in _cython_agg_general
    raise DataError('No numeric types to aggregate')
pandas.core.groupby.DataError: No numeric types to aggregate

**Comment by sdimi** [comment]
Please try adding an exception for the possibility of Null data ([see how here](http://stackoverflow.com/questions/42904971/python-error-no-numeric-types-to-aggregate-when-trying-to-use-df-resample)), or try to force recasting the column as numeric ([see how here](http://stackoverflow.com/questions/25397057/getting-average-of-pandas-with-groupby-getting-dataerror-no-numeric-types-to-a)). I hope it helps.

**Comment by Mustyy** [comment]
Like this?
tweets['created_at'] = pd.to_datetime(pd.Series(tweets['created_at'].astype(int)))

**Comment by sandrafdo** [comment]
import numpy as np
bookStats = ratings.groupby('title').agg({'rating': [np.size, np.mean]})
bookStats.head()

I get an error saying..
DataError: No numeric types to aggregate

**Comment by linehammer** [comment]
Did you initialize an empty DataFrame first and then filled it? If so that's probably why it changed with the new version as before 0.9 [empty DataFrame](http://net-informations.com/ds/pd/emptydf.htm) were initialized to float type but now they are of object type. If so you can change the initialization to DataFrame(dtype=float).

You can also call frame.astype(float)
